"""initial schema

Revision ID: 1109a63daa4e
Revises: 
Create Date: 2026-05-09 10:18:01.015831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1109a63daa4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_auction_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('auction_subtype', sa.String(length=32), server_default='estate', nullable=False),
    sa.Column('auctioneer_name', sa.String(length=255), nullable=True),
    sa.Column('auctioneer_external_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('terms_text', sa.Text(), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('pickup_city', sa.String(length=128), nullable=True),
    sa.Column('pickup_province', sa.String(length=8), nullable=True),
    sa.Column('pickup_window_text', sa.Text(), nullable=True),
    sa.Column('buyer_premium_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('online_bidding_fee_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('gst_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('pst_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='upcoming', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovery_confidence', sa.String(length=16), server_default='high', nullable=False),
    sa.Column('needs_plugin_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routing_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auctions')),
    sa.UniqueConstraint('source', 'source_auction_id', name='uq_auctions_source_source_auction_id')
    )
    op.create_index(op.f('ix_auctions_scheduled_end_at'), 'auctions', ['scheduled_end_at'], unique=False)
    op.create_index(op.f('ix_auctions_source'), 'auctions', ['source'], unique=False)
    op.create_index(op.f('ix_auctions_status'), 'auctions', ['status'], unique=False)
    op.create_table('historical_sales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('trim', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('transmission', sa.String(length=16), nullable=True),
    sa.Column('drivetrain', sa.String(length=16), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('title_status', sa.String(length=32), server_default='UNKNOWN', nullable=False),
    sa.Column('province_of_origin', sa.String(length=8), nullable=True),
    sa.Column('condition_categorical', sa.String(length=16), nullable=True),
    sa.Column('final_listed_price_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('days_listed', sa.Integer(), nullable=True),
    sa.Column('buyer_premium_pct_at_sale', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('final_price_with_premium_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_channel', sa.String(length=32), nullable=False),
    sa.Column('sale_platform', sa.String(length=64), nullable=False),
    sa.Column('seller_province', sa.String(length=8), nullable=True),
    sa.Column('seller_city', sa.String(length=128), nullable=True),
    sa.Column('observed_first_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disappeared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposition_reason', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('was_notified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('was_purchased_by_us', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historical_sales'))
    )
    op.create_index(op.f('ix_historical_sales_make'), 'historical_sales', ['make'], unique=False)
    op.create_index(op.f('ix_historical_sales_model'), 'historical_sales', ['model'], unique=False)
    op.create_index(op.f('ix_historical_sales_sale_channel'), 'historical_sales', ['sale_channel'], unique=False)
    op.create_index(op.f('ix_historical_sales_sale_platform'), 'historical_sales', ['sale_platform'], unique=False)
    op.create_index(op.f('ix_historical_sales_year'), 'historical_sales', ['year'], unique=False)
    op.create_table('searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), server_default='me', nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_searches'))
    )
    op.create_table('auction_lots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('auction_id', sa.BigInteger(), nullable=False),
    sa.Column('source_lot_id', sa.String(length=128), nullable=False),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('trim', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('transmission', sa.String(length=16), nullable=True),
    sa.Column('drivetrain', sa.String(length=16), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('title_status', sa.String(length=32), server_default='UNKNOWN', nullable=False),
    sa.Column('province_of_origin', sa.String(length=8), nullable=True),
    sa.Column('condition_categorical', sa.String(length=16), nullable=True),
    sa.Column('condition_confidence', sa.Float(), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('green_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('showstopper_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('carfax_url', sa.Text(), nullable=True),
    sa.Column('carfax_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desirable_trim_or_spec', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('classic_or_collector', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('desirability_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('desirability_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('historical_comp_count', sa.Integer(), nullable=True),
    sa.Column('recent_appreciation', sa.Float(), nullable=True),
    sa.Column('rarity_score', sa.Float(), nullable=True),
    sa.Column('vision_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vision_condition_overall', sa.String(length=16), nullable=True),
    sa.Column('vision_confidence', sa.Float(), nullable=True),
    sa.Column('vision_contradictions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('current_high_bid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_bid_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_count_visible', sa.Integer(), nullable=True),
    sa.Column('reserve_met', sa.Boolean(), nullable=True),
    sa.Column('lot_status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_bid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('comp_count', sa.Integer(), nullable=True),
    sa.Column('value_low_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_mid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_high_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_value_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('landed_cost_premium_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('all_in_at_current_bid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recommended_max_bid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_deal_score', sa.Float(), nullable=True),
    sa.Column('flag_score', sa.Integer(), nullable=True),
    sa.Column('confidence_bucket', sa.String(length=16), nullable=True),
    sa.Column('suspicious_underprice_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=True),
    sa.Column('weights_hash', sa.String(length=64), nullable=True),
    sa.Column('enrichment_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('valuation_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('vision_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('notification_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('enrichment_version', sa.String(length=32), nullable=True),
    sa.Column('early_warning_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cheap_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trajectory_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extended_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_channel', sa.String(length=64), nullable=True),
    sa.Column('user_action', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('was_purchased_by_us', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name=op.f('fk_auction_lots_auction_id_auctions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auction_lots')),
    sa.UniqueConstraint('auction_id', 'source_lot_id', name='uq_auction_lots_auction_source_lot')
    )
    op.create_index(op.f('ix_auction_lots_auction_id'), 'auction_lots', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auction_lots_enrichment_status'), 'auction_lots', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_auction_lots_lot_status'), 'auction_lots', ['lot_status'], unique=False)
    op.create_index(op.f('ix_auction_lots_make'), 'auction_lots', ['make'], unique=False)
    op.create_index('ix_auction_lots_make_model_year', 'auction_lots', ['make', 'model', 'year'], unique=False)
    op.create_index(op.f('ix_auction_lots_model'), 'auction_lots', ['model'], unique=False)
    op.create_index(op.f('ix_auction_lots_notification_status'), 'auction_lots', ['notification_status'], unique=False)
    op.create_index('ix_auction_lots_price_deal_score', 'auction_lots', ['price_deal_score', 'lot_status'], unique=False)
    op.create_index('ix_auction_lots_rarity_score', 'auction_lots', ['rarity_score'], unique=False)
    op.create_index(op.f('ix_auction_lots_user_action'), 'auction_lots', ['user_action'], unique=False)
    op.create_index(op.f('ix_auction_lots_valuation_status'), 'auction_lots', ['valuation_status'], unique=False)
    op.create_index(op.f('ix_auction_lots_vision_status'), 'auction_lots', ['vision_status'], unique=False)
    op.create_index(op.f('ix_auction_lots_was_purchased_by_us'), 'auction_lots', ['was_purchased_by_us'], unique=False)
    op.create_table('auction_bid_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_high_bid_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_time_at_observation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_at_observation', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], name=op.f('fk_auction_bid_history_lot_id_auction_lots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auction_bid_history'))
    )
    op.create_index(op.f('ix_auction_bid_history_lot_id'), 'auction_bid_history', ['lot_id'], unique=False)
    op.create_index('ix_bid_history_lot_observed', 'auction_bid_history', ['lot_id', 'observed_at'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('purchase_price_cad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price_cad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('province_of_purchase', sa.String(length=8), nullable=True),
    sa.Column('province_of_sale', sa.String(length=8), nullable=True),
    sa.Column('transport_cost_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inspection_cost_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('repair_cost_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_lot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_lot_id'], ['auction_lots.id'], name=op.f('fk_purchases_linked_lot_id_auction_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_index('ix_bid_history_lot_observed', table_name='auction_bid_history')
    op.drop_index(op.f('ix_auction_bid_history_lot_id'), table_name='auction_bid_history')
    op.drop_table('auction_bid_history')
    op.drop_index(op.f('ix_auction_lots_was_purchased_by_us'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_vision_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_valuation_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_user_action'), table_name='auction_lots')
    op.drop_index('ix_auction_lots_rarity_score', table_name='auction_lots')
    op.drop_index('ix_auction_lots_price_deal_score', table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_notification_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_model'), table_name='auction_lots')
    op.drop_index('ix_auction_lots_make_model_year', table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_make'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_lot_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_enrichment_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_auction_id'), table_name='auction_lots')
    op.drop_table('auction_lots')
    op.drop_table('searches')
    op.drop_index(op.f('ix_historical_sales_year'), table_name='historical_sales')
    op.drop_index(op.f('ix_historical_sales_sale_platform'), table_name='historical_sales')
    op.drop_index(op.f('ix_historical_sales_sale_channel'), table_name='historical_sales')
    op.drop_index(op.f('ix_historical_sales_model'), table_name='historical_sales')
    op.drop_index(op.f('ix_historical_sales_make'), table_name='historical_sales')
    op.drop_table('historical_sales')
    op.drop_index(op.f('ix_auctions_status'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_source'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_scheduled_end_at'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
