"""valuation_attempts and last_valuation_error

Revision ID: 1d58e4b5021c
Revises: 8544a8e57c2c
Create Date: 2026-05-09 22:15:59.400817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d58e4b5021c'
down_revision: Union[str, Sequence[str], None] = '8544a8e57c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_lots', sa.Column('valuation_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('auction_lots', sa.Column('last_valuation_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_lots', 'last_valuation_error')
    op.drop_column('auction_lots', 'valuation_attempts')
    # ### end Alembic commands ###
