"""want_matches ledger

Revision ID: 403d74523f36
Revises: a7d3a0c1e927
Create Date: 2026-06-27 15:21:13.977092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403d74523f36'
down_revision: Union[str, Sequence[str], None] = 'a7d3a0c1e927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('want_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('search_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('want_relative_score', sa.Float(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], name=op.f('fk_want_matches_lot_id_auction_lots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], name=op.f('fk_want_matches_search_id_searches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_want_matches')),
    sa.UniqueConstraint('search_id', 'lot_id', name='uq_want_matches_search_lot')
    )
    op.create_index(op.f('ix_want_matches_lot_id'), 'want_matches', ['lot_id'], unique=False)
    op.create_index(op.f('ix_want_matches_search_id'), 'want_matches', ['search_id'], unique=False)
    # NOTE: autogenerate also proposed dropping the functional UPPER() comp-lookup
    # indexes (ix_auction_lots/historical_sales_make_model_year_upper); those live
    # only in raw SQL in revision e5b8c1a4f273 (not in the model metadata), so the
    # drops are spurious and were removed by hand.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_want_matches_search_id'), table_name='want_matches')
    op.drop_index(op.f('ix_want_matches_lot_id'), table_name='want_matches')
    op.drop_table('want_matches')
    # ### end Alembic commands ###
