"""canonical_url + discovered_via + queue partial indexes

Revision ID: 54b9d983d047
Revises: 1109a63daa4e
Create Date: 2026-05-09 15:12:45.614055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54b9d983d047'
down_revision: Union[str, Sequence[str], None] = '1109a63daa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Partial indexes for queue-claim queries on auction_lots — one per status
    # field. Most rows are non-pending, so partial indexes are 10-100x smaller
    # than the full-table b-trees they replace.
    op.create_index(
        'ix_auction_lots_enrichment_pending', 'auction_lots', ['id'],
        unique=False, postgresql_where=sa.text("enrichment_status = 'pending'"),
    )
    op.create_index(
        'ix_auction_lots_notification_pending', 'auction_lots', ['id'],
        unique=False, postgresql_where=sa.text("notification_status = 'pending'"),
    )
    op.create_index(
        'ix_auction_lots_valuation_pending', 'auction_lots', ['id'],
        unique=False, postgresql_where=sa.text("valuation_status = 'pending'"),
    )
    op.create_index(
        'ix_auction_lots_vision_pending', 'auction_lots', ['id'],
        unique=False, postgresql_where=sa.text("vision_status = 'pending'"),
    )

    # canonical_url: three-step add (nullable + backfill + SET NOT NULL) so
    # this migration is safe whether or not auctions has rows.
    op.add_column('auctions', sa.Column('canonical_url', sa.Text(), nullable=True))
    op.execute("UPDATE auctions SET canonical_url = url WHERE canonical_url IS NULL")
    op.alter_column('auctions', 'canonical_url', nullable=False)
    op.create_index(
        op.f('ix_auctions_canonical_url'), 'auctions', ['canonical_url'], unique=False,
    )

    # discovered_via: nullable=False with server_default is safe on existing rows.
    op.add_column(
        'auctions',
        sa.Column(
            'discovered_via',
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_canonical_url'), table_name='auctions')
    op.drop_column('auctions', 'discovered_via')
    op.drop_column('auctions', 'canonical_url')
    op.drop_index('ix_auction_lots_vision_pending', table_name='auction_lots', postgresql_where=sa.text("vision_status = 'pending'"))
    op.drop_index('ix_auction_lots_valuation_pending', table_name='auction_lots', postgresql_where=sa.text("valuation_status = 'pending'"))
    op.drop_index('ix_auction_lots_notification_pending', table_name='auction_lots', postgresql_where=sa.text("notification_status = 'pending'"))
    op.drop_index('ix_auction_lots_enrichment_pending', table_name='auction_lots', postgresql_where=sa.text("enrichment_status = 'pending'"))
    # ### end Alembic commands ###
