"""enrichment_attempts and sparse_listing fields

Revision ID: 8544a8e57c2c
Revises: 54b9d983d047
Create Date: 2026-05-09 18:34:16.094552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8544a8e57c2c'
down_revision: Union[str, Sequence[str], None] = '54b9d983d047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_lots', sa.Column('enrichment_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('auction_lots', sa.Column('last_enrichment_error', sa.Text(), nullable=True))
    op.add_column('auction_lots', sa.Column('condition_inferred_from_sparse_listing', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('auction_lots', sa.Column('description_quality', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_lots', 'description_quality')
    op.drop_column('auction_lots', 'condition_inferred_from_sparse_listing')
    op.drop_column('auction_lots', 'last_enrichment_error')
    op.drop_column('auction_lots', 'enrichment_attempts')
    # ### end Alembic commands ###
